# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todolist.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0etodolist.proto\"\x12\n\x10ListTodosRequest\"1\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\")\n\x11ListTodosResponse\x12\x14\n\x05todos\x18\x01 \x03(\x0b\x32\x05.Todo\"(\n\x11\x43reateTodoRequest\x12\x13\n\x04todo\x18\x01 \x01(\x0b\x32\x05.Todo\":\n\x12\x43reateTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04todo\x18\x02 \x01(\x0b\x32\x05.Todo\",\n\x0f\x45\x64itTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"8\n\x10\x45\x64itTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04todo\x18\x02 \x01(\x0b\x32\x05.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x17UpdateTodoStatusRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x08\"@\n\x18UpdateTodoStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04todo\x18\x02 \x01(\x0b\x32\x05.Todo2\xa8\x02\n\x08TodoList\x12\x34\n\x0bGetAllTodos\x12\x11.ListTodosRequest\x1a\x12.ListTodosResponse\x12\x35\n\nCreateTodo\x12\x12.CreateTodoRequest\x1a\x13.CreateTodoResponse\x12/\n\x08\x45\x64itTodo\x12\x10.EditTodoRequest\x1a\x11.EditTodoResponse\x12\x35\n\nDeleteTodo\x12\x12.DeleteTodoRequest\x1a\x13.DeleteTodoResponse\x12G\n\x10UpdateTodoStatus\x12\x18.UpdateTodoStatusRequest\x1a\x19.UpdateTodoStatusResponseb\x06proto3'
)




_LISTTODOSREQUEST = _descriptor.Descriptor(
  name='ListTodosRequest',
  full_name='ListTodosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=36,
)


_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Todo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Todo.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Todo.status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=87,
)


_LISTTODOSRESPONSE = _descriptor.Descriptor(
  name='ListTodosResponse',
  full_name='ListTodosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='ListTodosResponse.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=130,
)


_CREATETODOREQUEST = _descriptor.Descriptor(
  name='CreateTodoRequest',
  full_name='CreateTodoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='CreateTodoRequest.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=172,
)


_CREATETODORESPONSE = _descriptor.Descriptor(
  name='CreateTodoResponse',
  full_name='CreateTodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='CreateTodoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='CreateTodoResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=232,
)


_EDITTODOREQUEST = _descriptor.Descriptor(
  name='EditTodoRequest',
  full_name='EditTodoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EditTodoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='EditTodoRequest.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=278,
)


_EDITTODORESPONSE = _descriptor.Descriptor(
  name='EditTodoResponse',
  full_name='EditTodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EditTodoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='EditTodoResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=336,
)


_DELETETODOREQUEST = _descriptor.Descriptor(
  name='DeleteTodoRequest',
  full_name='DeleteTodoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeleteTodoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=369,
)


_DELETETODORESPONSE = _descriptor.Descriptor(
  name='DeleteTodoResponse',
  full_name='DeleteTodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DeleteTodoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=408,
)


_UPDATETODOSTATUSREQUEST = _descriptor.Descriptor(
  name='UpdateTodoStatusRequest',
  full_name='UpdateTodoStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateTodoStatusRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='UpdateTodoStatusRequest.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=463,
)


_UPDATETODOSTATUSRESPONSE = _descriptor.Descriptor(
  name='UpdateTodoStatusResponse',
  full_name='UpdateTodoStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='UpdateTodoStatusResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='UpdateTodoStatusResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=529,
)

_LISTTODOSRESPONSE.fields_by_name['todos'].message_type = _TODO
_CREATETODOREQUEST.fields_by_name['todo'].message_type = _TODO
_CREATETODORESPONSE.fields_by_name['todo'].message_type = _TODO
_EDITTODORESPONSE.fields_by_name['todo'].message_type = _TODO
_UPDATETODOSTATUSRESPONSE.fields_by_name['todo'].message_type = _TODO
DESCRIPTOR.message_types_by_name['ListTodosRequest'] = _LISTTODOSREQUEST
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['ListTodosResponse'] = _LISTTODOSRESPONSE
DESCRIPTOR.message_types_by_name['CreateTodoRequest'] = _CREATETODOREQUEST
DESCRIPTOR.message_types_by_name['CreateTodoResponse'] = _CREATETODORESPONSE
DESCRIPTOR.message_types_by_name['EditTodoRequest'] = _EDITTODOREQUEST
DESCRIPTOR.message_types_by_name['EditTodoResponse'] = _EDITTODORESPONSE
DESCRIPTOR.message_types_by_name['DeleteTodoRequest'] = _DELETETODOREQUEST
DESCRIPTOR.message_types_by_name['DeleteTodoResponse'] = _DELETETODORESPONSE
DESCRIPTOR.message_types_by_name['UpdateTodoStatusRequest'] = _UPDATETODOSTATUSREQUEST
DESCRIPTOR.message_types_by_name['UpdateTodoStatusResponse'] = _UPDATETODOSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListTodosRequest = _reflection.GeneratedProtocolMessageType('ListTodosRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTODOSREQUEST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:ListTodosRequest)
  })
_sym_db.RegisterMessage(ListTodosRequest)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), {
  'DESCRIPTOR' : _TODO,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:Todo)
  })
_sym_db.RegisterMessage(Todo)

ListTodosResponse = _reflection.GeneratedProtocolMessageType('ListTodosResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTODOSRESPONSE,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:ListTodosResponse)
  })
_sym_db.RegisterMessage(ListTodosResponse)

CreateTodoRequest = _reflection.GeneratedProtocolMessageType('CreateTodoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETODOREQUEST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:CreateTodoRequest)
  })
_sym_db.RegisterMessage(CreateTodoRequest)

CreateTodoResponse = _reflection.GeneratedProtocolMessageType('CreateTodoResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETODORESPONSE,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:CreateTodoResponse)
  })
_sym_db.RegisterMessage(CreateTodoResponse)

EditTodoRequest = _reflection.GeneratedProtocolMessageType('EditTodoRequest', (_message.Message,), {
  'DESCRIPTOR' : _EDITTODOREQUEST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:EditTodoRequest)
  })
_sym_db.RegisterMessage(EditTodoRequest)

EditTodoResponse = _reflection.GeneratedProtocolMessageType('EditTodoResponse', (_message.Message,), {
  'DESCRIPTOR' : _EDITTODORESPONSE,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:EditTodoResponse)
  })
_sym_db.RegisterMessage(EditTodoResponse)

DeleteTodoRequest = _reflection.GeneratedProtocolMessageType('DeleteTodoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETETODOREQUEST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:DeleteTodoRequest)
  })
_sym_db.RegisterMessage(DeleteTodoRequest)

DeleteTodoResponse = _reflection.GeneratedProtocolMessageType('DeleteTodoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETETODORESPONSE,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:DeleteTodoResponse)
  })
_sym_db.RegisterMessage(DeleteTodoResponse)

UpdateTodoStatusRequest = _reflection.GeneratedProtocolMessageType('UpdateTodoStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETODOSTATUSREQUEST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:UpdateTodoStatusRequest)
  })
_sym_db.RegisterMessage(UpdateTodoStatusRequest)

UpdateTodoStatusResponse = _reflection.GeneratedProtocolMessageType('UpdateTodoStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETODOSTATUSRESPONSE,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:UpdateTodoStatusResponse)
  })
_sym_db.RegisterMessage(UpdateTodoStatusResponse)



_TODOLIST = _descriptor.ServiceDescriptor(
  name='TodoList',
  full_name='TodoList',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=532,
  serialized_end=828,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllTodos',
    full_name='TodoList.GetAllTodos',
    index=0,
    containing_service=None,
    input_type=_LISTTODOSREQUEST,
    output_type=_LISTTODOSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTodo',
    full_name='TodoList.CreateTodo',
    index=1,
    containing_service=None,
    input_type=_CREATETODOREQUEST,
    output_type=_CREATETODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EditTodo',
    full_name='TodoList.EditTodo',
    index=2,
    containing_service=None,
    input_type=_EDITTODOREQUEST,
    output_type=_EDITTODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='TodoList.DeleteTodo',
    index=3,
    containing_service=None,
    input_type=_DELETETODOREQUEST,
    output_type=_DELETETODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTodoStatus',
    full_name='TodoList.UpdateTodoStatus',
    index=4,
    containing_service=None,
    input_type=_UPDATETODOSTATUSREQUEST,
    output_type=_UPDATETODOSTATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOLIST)

DESCRIPTOR.services_by_name['TodoList'] = _TODOLIST

# @@protoc_insertion_point(module_scope)
