"""added columns created_at and last_updated_at

Revision ID: 551a7cb9c7b9
Revises: d8041628dc5d
Create Date: 2020-03-31 10:23:18.881941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551a7cb9c7b9'
down_revision = 'd8041628dc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'last_updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
